### ISSUE TITLE
Result on a large point cloud

### ISSUE THREAD

**Issue by Siziff** [unknownue/pdflow#5]
hello:) I'm trying to run your model on my data using your model weights but nothing changes. On the right is the original part of the plane on the left is the result of your model after 1 iteration. I also tried to run up to 2000 iterations, there were no changes. Could you tell me how you can improve the performance of your model for a large number of points (200 thousand +-), does it make sense to train on your own data or will it also not change anything?

![dd](https://user-images.githubusercontent.com/42972554/203500350-0e363ebd-dc8a-44ce-8e6d-4aa225b0e341.png)

![image](https://user-images.githubusercontent.com/42972554/203500471-9d505dd6-1666-4c81-9091-25875a0fdfed.png)

![image](https://user-images.githubusercontent.com/42972554/203500568-e158e559-79da-4532-865e-e6bcda8b0927.png)

**Comment by unknownue** [comment]
Generally, this work(and other SOTA works) are trying to generate uniform and smooth surface for point **PATCH**. Here, denoising means that the neural networks try to transform the point patch to pattern similar to ground-truth training data.
However, denoising large point clouds (20000+ points) is another story. When dealing with **large** point clouds by patch-based denoising methods, it is difficult to:
1. design reasonable methods to merge denoised patches (especially on removing duplicate points on patch edge after merge).
2. adapt similar noise level between extracted patch and training patch.

One can employ some technical hacks to make the results look good on large point cloud, but these hacks are not generic and not counted as the contributions of an academic paper. This problem is hard to solve in term of neural networks, because neural networks need fixed input size of data as training.
This work (and other SOTA works before this paper was published) do not provide a robust solution to this problem, and the technical details to handle large point clouds are not related to main idea of these papers.
I will appreciate if anyone can come up with a solution from academic side.
